baseURL = 'https://test.wyll.io/'
languageCode = 'fr-fr'
title = 'Wyll - DevOps Cloud Data - Toulouse - Montpellier - Bordeaux'

[build]
  writeStats = true

[deployment]

[[deployment.targets]]
name = "test.wyll.io"
URL = "s3://test.wyll.io?region=eu-west-3"
cloudFrontDistributionID = "E2TAX61U0ZN76O"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true