name: Deploy website on AWS S3

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: AWS authentication and role assume
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: eu-west-3
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-session-name: MySessionName
        role-duration-seconds: 1200
    - name: Sync files to S3 bucket
      run: aws s3 sync . s3://io.wyll/ --delete 
    # Clears the CloudFront cache so new requests will receive the latest version of your app
    - name: Invalidate Cloudfront
      uses: chetan/invalidate-cloudfront-action@v1.3
      env:
        DISTRIBUTION: 'E33J6UZAJVOQ9V'
        PATHS: '/*'
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: MySessionName
        role-duration-seconds: 1200
        AWS_REGION: 'eu-west-3'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
